version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://user:password@db:5432/splitit-db
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: splitit-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: